config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :countries, param: :name, shallow: true do
    resources :states, shallow: true do
      resources :cities, shallow: true do
        resources :neighborhoods, shallow: true do
          resources :streets, shallow: true do
            resources :addresses, shallow: true
          end
        end
      end
    end
  end

  resources :publishers
  resources :genres
  resources :authors
  resources :books
  resources :users
  resources :exchanges
  resources :evaluations
  resources :messages
  resources :badges

  resources :queries, only: [:index] do
    get 'top_titles', on: :collection
    get 'top_contributors', on: :collection
    get 'top_exchanged_books', on: :collection
    get 'top_authors', on: :collection
    get 'pagenometer', on: :collection
  end

  resources :views, only: [:index] do
    get 'books_info', 'book_owners', on: :collection
  end

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :badge
  belongs_to :user
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :street
  has_many :publishers, dependent: :nullify
  validates_presence_of :number, :complement, :cep
end

app/models/author.rb
class Author < ActiveRecord::Base

  self.primary_key = 'cpf'

  include AuthorConcern

  validates_presence_of :name, :cpf, :birth_date
  has_many :books, dependent: :nullify, foreign_key: 'author_cpf'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :achievements, dependent: :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base

  include BookConcern

  belongs_to :genre
  belongs_to :publisher, foreign_key: 'publisher_cnpj'
  belongs_to :author, foreign_key: 'author_cpf'
  has_many :evaluations, dependent: :destroy, foreign_key: 'book_isbn'

  self.primary_key = 'isbn'

  validates_presence_of :pages, :isbn, :name, :publish_date, :edition, :publisher_cnpj, :genre_id, :author_cpf

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :neighborhoods, dependent: :destroy
  validates_presence_of :name
end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :states, foreign_key: 'country_name', dependent: :destroy

  self.primary_key = 'name'

  validates_presence_of :name

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base

  belongs_to :user, foreign_key: 'user_username'
  belongs_to :book, foreign_key: 'book_isbn'

  validates_presence_of :points, :comment

  def cool_id
    "#{book_isbn}-#{user_username}"
  end

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base

  belongs_to :user_a, class_name: 'User', foreign_key: 'user_a_username'
  belongs_to :user_b, class_name: 'User', foreign_key: 'user_b_username'
  belongs_to :book_a, class_name: 'Book', foreign_key: 'book_a_isbn'
  belongs_to :book_b, class_name: 'Book', foreign_key: 'book_b_isbn'

  validates_presence_of :user_a_username, :user_b_username, :book_a_isbn, :book_b_isbn

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  validates_presence_of :name
  has_many :books, dependent: :nullify

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :addressee, class_name: 'User', foreign_key: 'addressee_username'
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_username'

  validates_presence_of :date, :body, :addressee_username, :sender_username

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  has_many :streets, dependent: :destroy
  validates_presence_of :name
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base

  belongs_to :address
  has_many :books, dependent: :nullify, foreign_key: 'publisher_cnpj'
end

app/models/state.rb
class State < ActiveRecord::Base

  belongs_to :country, foreign_key: 'country_name'
  has_many :cities, dependent: :destroy

  validates_presence_of :name

end

app/models/street.rb
class Street < ActiveRecord::Base
  belongs_to :neighborhood
  has_many :addresses, dependent: :destroy
  validates_presence_of :name, :kind
end

app/models/telephone.rb
class Telephone < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  self.primary_key = 'username'

  include UserConcern

  has_many :evaluations, dependent: :destroy, foreign_key: 'user_username'
  has_many :exchanges_a, dependent: :nullify, foreign_key: 'user_a_username', class_name: 'Exchange'
  has_many :exchanges_b, dependent: :nullify, foreign_key: 'user_b_username', class_name: 'Exchange'
  has_many :messages_addressee, dependent: :destroy, foreign_key: 'addressee_username', class_name: 'Message'
  has_many :messages_sender, dependent: :destroy, foreign_key: 'sender_username', class_name: 'Message'
  has_many :achievements, foreign_key: 'user_username', dependent: :destroy
  has_many :badges, through: :achievements

  validates_presence_of :name, :email, :username, :password

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all.order(name: :asc)
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def books_options_for_select
    books = Book.all
    books.map { |book| [book.name, book.isbn] }
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def users_options_for_select
    users = User.all
    users.map { |user| [user.name, user.username] }
  end

end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/badges/_form.html.erb
<%= render 'layouts/errors', resource: @badge %>

<%= form_for(@badge, html: {class: 'form-horizontal'}) do |f| %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-3 control-label' %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name', required: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-10">
        <%= f.submit class: 'btn btn-success pull-right' %>
        <%= link_to 'Back', badges_path, class: 'btn btn-warning pull-right', style: 'margin-right: 10px' %>
      </div>
    </div>

<% end %>

app/views/badges/index.html.erb
<%= render 'layouts/list_header' %>

<%= render 'layouts/flash_success' %>

<div class="row">

  <div class="col-sm-12">

    <div class="table-responsive">

      <table class="table table-bordered table-hover">

        <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @badges.each do |badge| %>
            <tr>
              <td><%= badge.name %></td>
              <td><%= link_to 'Show', badge, class: 'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Edit', edit_badge_path(badge), class: 'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
            </tr>
        <% end %>
        </tbody>

      </table>

    </div>

  </div>

</div>

app/views/badges/show.html.erb
<%= render 'layouts/show_header' %>

<%= render 'layouts/flash_success' %>

<div class="row">

  <div class="col-sm-12">

    <div class="well">

      <div>
        <strong>Name:</strong>
        <%= @badge.name %>
      </div>

    </div>

  </div>

</div>

<div class="row">
  <div class="col-sm-12">
    <%= link_to 'Edit', edit_badge_path(@badge), class: 'btn btn-primary btn-xs' %>
    <%= link_to 'Back', badges_path, class: 'btn btn-warning btn-xs' %>
  </div>
</div>